<?php


namespace diazoxide\wp\lib\option\fields;


class Number extends Input
{

    public $type = 'number';
    public $min;
    public $max;

    protected function validate(): bool
    {
        $this->attrs['min'] = $this->min;
        $this->attrs['max'] = $this->min;

        return parent::validate(); // TODO: Change the autogenerated stub
    }
}